from enum import Enum


class Emojis(Enum):
    """Enum com emojis comuns para uso na aplicação."""
    
    # Status e feedback
    SUCCESS = "✅"
    ERROR = "❌"
    WARNING = "⚠️"
    INFO = "ℹ️"
    QUESTION = "❓"
    CHECK = "✔️"
    CROSS = "✖️"
    EXCLAMATION = "❗"
    ATTENTION = "⚡"
    STOP = "🛑"
    PROHIBITED = "🚫"
    LOADING = "⏳"
    REFRESH = "🔄"
    
    # Ações
    SEARCH = "🔍"
    EDIT = "✏️"
    DELETE = "🗑️"
    SAVE = "💾"
    DOWNLOAD = "⬇️"
    UPLOAD = "⬆️"
    COPY = "📋"
    LINK = "🔗"
    ADD = "➕"
    REMOVE = "➖"
    PLUS = "+"
    MINUS = "−"
    PLAY = "▶️"
    PAUSE = "⏸️"
    STOP_BUTTON = "⏹️"
    RECORD = "⏺️"
    FAST_FORWARD = "⏩"
    REWIND = "⏪"
    SHUFFLE = "🔀"
    REPEAT = "🔁"
    PRINT = "🖨️"
    SHARE = "🔗"
    EXPORT = "📤"
    IMPORT = "📥"
    
    # Navegação
    HOME = "🏠"
    SETTINGS = "⚙️"
    MENU = "☰"
    BACK = "⬅️"
    FORWARD = "➡️"
    UP = "⬆️"
    DOWN = "⬇️"
    LEFT = "⬅️"
    RIGHT = "➡️"
    TOP = "🔝"
    END = "🔚"
    ARROW_UP = "⏫"
    ARROW_DOWN = "⏬"
    DOUBLE_UP = "⏫"
    DOUBLE_DOWN = "⏬"
    
    # Documentos e arquivos
    FILE = "📄"
    FOLDER = "📁"
    DOCUMENT = "📝"
    IMAGE = "🖼️"
    PDF = "📕"
    BOOK = "📖"
    NOTEBOOK = "📓"
    PAGE = "📃"
    BOOKMARK = "🔖"
    CLIP = "📎"
    PIN = "📌"
    ZIP = "🗜️"
    PACKAGE = "📦"
    BOX = "📦"
    ARCHIVE = "🗄️"
    
    # Comunicação
    EMAIL = "📧"
    MESSAGE = "💬"
    NOTIFICATION = "🔔"
    PHONE = "📞"
    MOBILE = "📱"
    SPEECH = "💭"
    COMMENT = "💬"
    INBOX = "📥"
    OUTBOX = "📤"
    ENVELOPE = "✉️"
    MEGAPHONE = "📣"
    LOUDSPEAKER = "📢"
    
    # Usuário e perfil
    USER = "👤"
    USERS = "👥"
    PROFILE = "👨‍💼"
    LOGIN = "🔐"
    LOGOUT = "🚪"
    ADMIN = "👨‍💻"
    EMPLOYEE = "👨‍💼"
    CUSTOMER = "🧑‍💼"
    TEAM = "👨‍👩‍👧‍👦"
    PERSON = "🧑"
    BADGE = "🎫"
    ID_CARD = "🪪"
    
    # Tempo
    CLOCK = "🕐"
    CALENDAR = "📅"
    TIMER = "⏱️"
    HOURGLASS = "⌛"
    ALARM = "⏰"
    WATCH = "⌚"
    STOPWATCH = "⏱️"
    DATE = "📆"
    SCHEDULE = "🗓️"
    
    # Indicadores
    STAR = "⭐"
    HEART = "❤️"
    FIRE = "🔥"
    ROCKET = "🚀"
    TARGET = "🎯"
    TROPHY = "🏆"
    MEDAL = "🏅"
    CROWN = "👑"
    GEM = "💎"
    SPARKLES = "✨"
    THUMBS_UP = "👍"
    THUMBS_DOWN = "👎"
    CLAP = "👏"
    WAVE = "👋"
    CELEBRATION = "🎉"
    PARTY = "🎊"
    BALLOON = "🎈"
    
    # Ferramentas
    TOOL = "🔧"
    HAMMER = "🔨"
    KEY = "🔑"
    LOCK = "🔒"
    UNLOCK = "🔓"
    WRENCH = "🔧"
    SCREWDRIVER = "🪛"
    MAGNET = "🧲"
    MICROSCOPE = "🔬"
    TELESCOPE = "🔭"
    BATTERY = "🔋"
    PLUGIN = "🔌"
    GEAR = "⚙️"
    
    # Dados e gráficos
    CHART = "📊"
    GRAPH = "📈"
    DECREASE = "📉"
    PIE_CHART = "🥧"
    BAR_CHART = "📊"
    LINE_CHART = "📈"
    DASHBOARD = "🎛️"
    DATABASE = "🗄️"
    SERVER = "🖥️"
    COMPUTER = "💻"
    LAPTOP = "💻"
    DESKTOP = "🖥️"
    KEYBOARD = "⌨️"
    MOUSE = "🖱️"
    PRINTER = "🖨️"
    
    # Outros úteis
    LIGHT_BULB = "💡"
    GIFT = "🎁"
    MONEY = "💰"
    GLOBE = "🌐"
    MAGIC = "✨"
    ROBOT = "🤖"
    CAMERA = "📷"
    VIDEO = "📹"
    MUSIC = "🎵"
    HEADPHONE = "🎧"
    MICROPHONE = "🎤"
    PAINT = "🎨"
    BRUSH = "🖌️"
    CRAYON = "🖍️"
    SCISSORS = "✂️"
    RULER = "📏"
    CALCULATOR = "🧮"
    SHOPPING = "🛒"
    CART = "🛒"
    BAG = "👜"
    BRIEFCASE = "💼"
    CREDIT_CARD = "💳"
    RECEIPT = "🧾"
    LABEL = "🏷️"
    PRICE_TAG = "🏷️"
    COIN = "🪙"
    DOLLAR = "💵"
    CHART_UP = "📈"
    CHART_DOWN = "📉"
    PERCENTAGE = "💯"
    FLAG = "🚩"
    BOOKMARK_TAB = "🔖"
    THOUGHT = "💭"
    ZZZ = "💤"
    BOOM = "💥"
    SWEAT = "💦"
    DASH = "💨"
    DIZZY = "💫"
    BRAIN = "🧠"
    EYE = "👁️"
    HAND = "✋"
    FINGER_POINT = "☝️"
    WRITING = "✍️"
    
    # Natureza
    SUN = "☀️"
    MOON = "🌙"
    STAR_NATURE = "⭐"
    CLOUD = "☁️"
    RAIN = "🌧️"
    SNOW = "❄️"
    THUNDER = "⚡"
    WIND = "💨"
    WATER = "💧"
    FIRE_ELEMENT = "🔥"
    TREE = "🌳"
    PLANT = "🌱"
    FLOWER = "🌸"
    LEAF = "🍃"
    
    # Comida e bebida
    COFFEE = "☕"
    TEA = "🍵"
    BEER = "🍺"
    WINE = "🍷"
    PIZZA = "🍕"
    BURGER = "🍔"
    CAKE = "🍰"
    COOKIE = "🍪"
    APPLE = "🍎"
    BANANA = "🍌"
    
    # Transporte
    CAR = "🚗"
    BUS = "🚌"
    TRAIN = "🚆"
    PLANE = "✈️"
    BIKE = "🚲"
    SHIP = "🚢"
    TRUCK = "🚚"
    
    # Locais
    BUILDING = "🏢"
    HOUSE = "🏠"
    HOSPITAL = "🏥"
    SCHOOL = "🏫"
    BANK = "🏦"
    HOTEL = "🏨"
    FACTORY = "🏭"
    STORE = "🏪"
    
    def __str__(self):
        """Retorna o emoji como string."""
        return self.value
